### ISSUE TITLE
Error while building with Gromacs

### ISSUE THREAD

**Issue by Madhur-mamaji** [MICCoM/SSAGES-public#11]
Hi,
I am building SSAGES with Gromacs (by installing Gromacs along with SSAGES) and getting the following error:

Cloning into 'gromacs-download'...
fatal: unable to connect to git.gromacs.org:
git.gromacs.org[0: 130.237.25.132]: errno=Connection refused
git.gromacs.org[1: 2001:6b0:1:1190:5054:ff:fed2:2481]: errno=Network is unreachable

I tried opening git.gromacs.org in my browser (without as well as without proxy) and it says the requested URL cannot be retrieved. I think this link has been changed which needs to be updated in one of the installation scripts of SSAGES.

If Gromacs is already installed, then there's no problem in building the SSAGES executable file.

Please look into this.

Thanks a lot.

**Comment by mquevill** [comment]
There's a chance that the GROMACS Git repository was down when you were trying to connect. We have not encountered any issues with this repository address in the past. I just ran a test with a fresh build, and the clone progressed as expected. If this issue persists, it may be due to some settings on your machine with either Git or a proxy.

The URL of `git.gromacs.org` will not be accessible from a regular browser, as it is not the same standard as normal webpages. This uses `git://` instead of `https://`, so it is expected behavior that no page would load there.

If you would like additional help, please also include the `cmake` command (with flags, etc.) and the version number of Git you are using, since that seems to be where the issue is occuring.

**Comment by mquevill** [comment]
If the cloning of GROMACS is still not working, I would suggest downloading a version on your own (5.1 or later) and passing in the path as `-DGROMACS_SRC=/path/to/gromacs` instead of using `-DGROMACS`.

Please reopen this issue if you are still having trouble.
