### ISSUE TITLE
Build Error with HOOMD-2.4.0

### ISSUE THREAD

**Issue by nsherrin** [MICCoM/SSAGES-public#13]
Dear SSAGES developers,

I am running into an error for ExecutionConfiguration when trying to build SSAGES-0.8.4 with HOOMD-2.4.0. Any help would be greatly appreciated, thanks!

[make_SSAGES.log](https://github.com/MICCoM/SSAGES-public/files/3164377/make_SSAGES.log)
[Cmake.log](https://github.com/MICCoM/SSAGES-public/files/3164379/Cmake.log)

**Comment by mquevill** [comment]
It appears that there was a change between the development version that we were using and the actual release of 2.4.0. I've included a simple change (see below) to be made that should fix this issue. Basically HOOMD now takes a vector of GPU ids instead of just an index.

I tested with v2.4.0 and v2.5.2 and it should compile. This will be incorporated into the next release of SSAGES.

hooks/hoomd/Driver.cpp
```diff
@@ -118,7 +118,7 @@ namespace SSAGES
          auto exec_conf = std::make_shared<ExecutionConfiguration>(
-         execution_mode, -1, false, false,
+         execution_mode, std::vector<int>{-1}, false, false,
          std::shared_ptr<Messenger>(), 0, rh->GetLocalComm());
```

Let us know if you have any other troubles while compiling.
