### ISSUE TITLE
Error in `make` while trying to get SSAGES executable

### ISSUE THREAD

**Issue by wisecashew** [MICCoM/SSAGES-public#47]
I am following the procedure laid out [on this page](https://github.com/SSAGESproject/SSAGES). 

I am using the LAMMPS version released on Sep 29, 2021 with the ASPHERE, EXTRA_MOLECULE, and CLASS2 package with icc and icpc as my C and CXX compilers. 

However, as I try to `make` SSAGES, I get the following error:
```
[ 42%] Building CXX object CMakeFiles/libssages.dir/hooks/lammps/fix_ssages.cpp.o
/home/user/software/SSAGES/hooks/lammps/fix_ssages.cpp(34): error: identifier "virial_flag" is undefined
  		virial_flag = 1;
  		^

/home/user/software/SSAGES/hooks/lammps/fix_ssages.cpp(87): error: identifier "THERMO_ENERGY" is undefined
  		mask |= THERMO_ENERGY;
  		        ^

compilation aborted for /home/user/software/SSAGES/hooks/lammps/fix_ssages.cpp (code 2)
make[2]: *** [CMakeFiles/libssages.dir/build.make:76: CMakeFiles/libssages.dir/hooks/lammps/fix_ssages.cpp.o] Error 2
make[1]: *** [CMakeFiles/Makefile2:370: CMakeFiles/libssages.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```
How do I fix this issue? Is there an issue with virial_flag? I would appreciate any advice you have for me.

**Comment by mquevill** [comment]
The developers of LAMMPS made some changes since there were inconsistencies associated with those variables. It seems like the 29 Sep 2021 release and all newer releases will be affected by these changes. This would require us to rewrite parks of our engine hook to address these changes. SSAGES has been extensively tested with stable versions from 10 Aug 2015 to 29 Oct 2020, so I would recommend using one of those versions, if possible.

Original issue raised here: https://github.com/lammps/lammps/issues/2528
Code changes were put into LAMMPS here: https://github.com/lammps/lammps/pull/2560
Longer discussion that first gave rise to noticing these inconsistencies: https://github.com/lammps/lammps/pull/2515

**Comment by wisecashew** [comment]
Thank you @mquevill. I tried out LAMMPS 29Oct2020 with the packages I need and ssages has compiled.
